// @generated by protoc-gen-es v2.7.0
// @generated from file nimbus_public/v1/main.proto (package nimbus_public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nimbus_public/v1/main.proto.
 */
export declare const file_nimbus_public_v1_main: GenFile;

/**
 * The details of any object it can be file or a directory and the access url if the object is public otherwise it can be only access via personal access token.
 *
 * @generated from message nimbus_public.v1.ObjectDetails
 */
export declare type ObjectDetails = Message<"nimbus_public.v1.ObjectDetails"> & {
  /**
   * @generated from field: nimbus_public.v1.ObjectType object_type = 1;
   */
  objectType: ObjectType;

  /**
   * @generated from field: string object_id = 2;
   */
  objectId: string;

  /**
   * @generated from field: uint64 object_size = 3;
   */
  objectSize: bigint;

  /**
   * @generated from field: nimbus_public.v1.AccessType access_type = 4;
   */
  accessType: AccessType;

  /**
   * @generated from field: string created_on = 5;
   */
  createdOn: string;

  /**
   * image/jpeg, image/png, text/plain
   *
   * @generated from field: string content_type = 6;
   */
  contentType: string;

  /**
   * @generated from field: map<string, string> meta_data = 7;
   */
  metaData: { [key: string]: string };

  /**
   * The access url of a directory is referd as static directory which serve static contents.
   *
   * @generated from field: optional string access_url = 8;
   */
  accessUrl?: string;
};

/**
 * Describes the message nimbus_public.v1.ObjectDetails.
 * Use `create(ObjectDetailsSchema)` to create a new message.
 */
export declare const ObjectDetailsSchema: GenMessage<ObjectDetails>;

/**
 * Stream of bytes of the file.
 *
 * @generated from message nimbus_public.v1.PutObjectRequest
 */
export declare type PutObjectRequest = Message<"nimbus_public.v1.PutObjectRequest"> & {
  /**
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;
};

/**
 * Describes the message nimbus_public.v1.PutObjectRequest.
 * Use `create(PutObjectRequestSchema)` to create a new message.
 */
export declare const PutObjectRequestSchema: GenMessage<PutObjectRequest>;

/**
 * After sending the bytes either getting the object response or the error message from the server.
 *
 * @generated from message nimbus_public.v1.PutObjectResponse
 */
export declare type PutObjectResponse = Message<"nimbus_public.v1.PutObjectResponse"> & {
  /**
   * @generated from field: nimbus_public.v1.ObjectDetails object_details = 1;
   */
  objectDetails?: ObjectDetails;
};

/**
 * Describes the message nimbus_public.v1.PutObjectResponse.
 * Use `create(PutObjectResponseSchema)` to create a new message.
 */
export declare const PutObjectResponseSchema: GenMessage<PutObjectResponse>;

/**
 * Object id is like the file id, this id must be a file path not a directory or invalid file name.
 *
 * @generated from message nimbus_public.v1.GetObjectRequest
 */
export declare type GetObjectRequest = Message<"nimbus_public.v1.GetObjectRequest"> & {
  /**
   * @generated from field: string object_id = 1;
   */
  objectId: string;
};

/**
 * Describes the message nimbus_public.v1.GetObjectRequest.
 * Use `create(GetObjectRequestSchema)` to create a new message.
 */
export declare const GetObjectRequestSchema: GenMessage<GetObjectRequest>;

/**
 * @generated from message nimbus_public.v1.GetObjectResponse
 */
export declare type GetObjectResponse = Message<"nimbus_public.v1.GetObjectResponse"> & {
  /**
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;
};

/**
 * Describes the message nimbus_public.v1.GetObjectResponse.
 * Use `create(GetObjectResponseSchema)` to create a new message.
 */
export declare const GetObjectResponseSchema: GenMessage<GetObjectResponse>;

/**
 * Delete objects
 *
 * @generated from message nimbus_public.v1.DeleteObjectRequest
 */
export declare type DeleteObjectRequest = Message<"nimbus_public.v1.DeleteObjectRequest"> & {
  /**
   * @generated from field: repeated string object_ids = 1;
   */
  objectIds: string[];
};

/**
 * Describes the message nimbus_public.v1.DeleteObjectRequest.
 * Use `create(DeleteObjectRequestSchema)` to create a new message.
 */
export declare const DeleteObjectRequestSchema: GenMessage<DeleteObjectRequest>;

/**
 * @generated from message nimbus_public.v1.DeleteObjectResponse
 */
export declare type DeleteObjectResponse = Message<"nimbus_public.v1.DeleteObjectResponse"> & {
  /**
   * @generated from field: repeated string object_ids = 1;
   */
  objectIds: string[];
};

/**
 * Describes the message nimbus_public.v1.DeleteObjectResponse.
 * Use `create(DeleteObjectResponseSchema)` to create a new message.
 */
export declare const DeleteObjectResponseSchema: GenMessage<DeleteObjectResponse>;

/**
 * Update access type
 *
 * @generated from message nimbus_public.v1.UpdateAccessTypeRequest
 */
export declare type UpdateAccessTypeRequest = Message<"nimbus_public.v1.UpdateAccessTypeRequest"> & {
  /**
   * @generated from field: repeated string object_ids = 1;
   */
  objectIds: string[];

  /**
   * @generated from field: nimbus_public.v1.AccessType access_type = 2;
   */
  accessType: AccessType;
};

/**
 * Describes the message nimbus_public.v1.UpdateAccessTypeRequest.
 * Use `create(UpdateAccessTypeRequestSchema)` to create a new message.
 */
export declare const UpdateAccessTypeRequestSchema: GenMessage<UpdateAccessTypeRequest>;

/**
 * @generated from message nimbus_public.v1.UpdateAccessTypeResponse
 */
export declare type UpdateAccessTypeResponse = Message<"nimbus_public.v1.UpdateAccessTypeResponse"> & {
  /**
   * @generated from field: repeated nimbus_public.v1.UpdateAccessTypeResponse.ObjectAccessInfo object_access_info = 1;
   */
  objectAccessInfo: UpdateAccessTypeResponse_ObjectAccessInfo[];
};

/**
 * Describes the message nimbus_public.v1.UpdateAccessTypeResponse.
 * Use `create(UpdateAccessTypeResponseSchema)` to create a new message.
 */
export declare const UpdateAccessTypeResponseSchema: GenMessage<UpdateAccessTypeResponse>;

/**
 * The access information of an object it can be used via public url or only access using personal access token.
 *
 * @generated from message nimbus_public.v1.UpdateAccessTypeResponse.ObjectAccessInfo
 */
export declare type UpdateAccessTypeResponse_ObjectAccessInfo = Message<"nimbus_public.v1.UpdateAccessTypeResponse.ObjectAccessInfo"> & {
  /**
   * @generated from field: string object_id = 1;
   */
  objectId: string;

  /**
   * @generated from field: nimbus_public.v1.AccessType access_type = 2;
   */
  accessType: AccessType;

  /**
   * @generated from field: optional string access_url = 3;
   */
  accessUrl?: string;
};

/**
 * Describes the message nimbus_public.v1.UpdateAccessTypeResponse.ObjectAccessInfo.
 * Use `create(UpdateAccessTypeResponse_ObjectAccessInfoSchema)` to create a new message.
 */
export declare const UpdateAccessTypeResponse_ObjectAccessInfoSchema: GenMessage<UpdateAccessTypeResponse_ObjectAccessInfo>;

/**
 * Get directory content.
 *
 * @generated from message nimbus_public.v1.GetDirectoryContentRequest
 */
export declare type GetDirectoryContentRequest = Message<"nimbus_public.v1.GetDirectoryContentRequest"> & {
  /**
   * If no directory given returns the root system.
   *
   * @generated from field: optional string object_id = 1;
   */
  objectId?: string;

  /**
   * @generated from field: string off_set = 2;
   */
  offSet: string;

  /**
   * @generated from field: string count = 3;
   */
  count: string;
};

/**
 * Describes the message nimbus_public.v1.GetDirectoryContentRequest.
 * Use `create(GetDirectoryContentRequestSchema)` to create a new message.
 */
export declare const GetDirectoryContentRequestSchema: GenMessage<GetDirectoryContentRequest>;

/**
 * @generated from message nimbus_public.v1.GetDirectoryContentResponse
 */
export declare type GetDirectoryContentResponse = Message<"nimbus_public.v1.GetDirectoryContentResponse"> & {
  /**
   * @generated from field: uint64 object_count = 1;
   */
  objectCount: bigint;

  /**
   * @generated from field: repeated nimbus_public.v1.GetDirectoryContentResponse.ObjectInfo objects = 4;
   */
  objects: GetDirectoryContentResponse_ObjectInfo[];
};

/**
 * Describes the message nimbus_public.v1.GetDirectoryContentResponse.
 * Use `create(GetDirectoryContentResponseSchema)` to create a new message.
 */
export declare const GetDirectoryContentResponseSchema: GenMessage<GetDirectoryContentResponse>;

/**
 * @generated from message nimbus_public.v1.GetDirectoryContentResponse.ObjectInfo
 */
export declare type GetDirectoryContentResponse_ObjectInfo = Message<"nimbus_public.v1.GetDirectoryContentResponse.ObjectInfo"> & {
  /**
   * @generated from field: string object_id = 1;
   */
  objectId: string;

  /**
   * @generated from field: nimbus_public.v1.AccessType access_type = 2;
   */
  accessType: AccessType;

  /**
   * @generated from field: nimbus_public.v1.ObjectType object_type = 3;
   */
  objectType: ObjectType;

  /**
   * @generated from field: string content_type = 4;
   */
  contentType: string;

  /**
   * @generated from field: string created_on = 5;
   */
  createdOn: string;
};

/**
 * Describes the message nimbus_public.v1.GetDirectoryContentResponse.ObjectInfo.
 * Use `create(GetDirectoryContentResponse_ObjectInfoSchema)` to create a new message.
 */
export declare const GetDirectoryContentResponse_ObjectInfoSchema: GenMessage<GetDirectoryContentResponse_ObjectInfo>;

/**
 * Find object by id
 *
 * @generated from message nimbus_public.v1.FindObjectByIdRequest
 */
export declare type FindObjectByIdRequest = Message<"nimbus_public.v1.FindObjectByIdRequest"> & {
  /**
   * @generated from field: string object_id = 1;
   */
  objectId: string;
};

/**
 * Describes the message nimbus_public.v1.FindObjectByIdRequest.
 * Use `create(FindObjectByIdRequestSchema)` to create a new message.
 */
export declare const FindObjectByIdRequestSchema: GenMessage<FindObjectByIdRequest>;

/**
 * @generated from message nimbus_public.v1.FindObjectByIdResponse
 */
export declare type FindObjectByIdResponse = Message<"nimbus_public.v1.FindObjectByIdResponse"> & {
  /**
   * @generated from field: nimbus_public.v1.ObjectDetails object = 1;
   */
  object?: ObjectDetails;
};

/**
 * Describes the message nimbus_public.v1.FindObjectByIdResponse.
 * Use `create(FindObjectByIdResponseSchema)` to create a new message.
 */
export declare const FindObjectByIdResponseSchema: GenMessage<FindObjectByIdResponse>;

/**
 * RenameFile 
 *
 * @generated from message nimbus_public.v1.RenameFileRequest
 */
export declare type RenameFileRequest = Message<"nimbus_public.v1.RenameFileRequest"> & {
  /**
   * @generated from field: repeated string object_ids = 1;
   */
  objectIds: string[];

  /**
   * @generated from field: optional string destination = 2;
   */
  destination?: string;
};

/**
 * Describes the message nimbus_public.v1.RenameFileRequest.
 * Use `create(RenameFileRequestSchema)` to create a new message.
 */
export declare const RenameFileRequestSchema: GenMessage<RenameFileRequest>;

/**
 * @generated from message nimbus_public.v1.RenameFileResponse
 */
export declare type RenameFileResponse = Message<"nimbus_public.v1.RenameFileResponse"> & {
  /**
   * @generated from field: repeated string object_ids = 1;
   */
  objectIds: string[];
};

/**
 * Describes the message nimbus_public.v1.RenameFileResponse.
 * Use `create(RenameFileResponseSchema)` to create a new message.
 */
export declare const RenameFileResponseSchema: GenMessage<RenameFileResponse>;

/**
 * Copy files
 *
 *
 * @generated from message nimbus_public.v1.CopyFileRequest
 */
export declare type CopyFileRequest = Message<"nimbus_public.v1.CopyFileRequest"> & {
  /**
   * @generated from field: repeated string object_ids = 1;
   */
  objectIds: string[];

  /**
   * @generated from field: optional string destination = 2;
   */
  destination?: string;
};

/**
 * Describes the message nimbus_public.v1.CopyFileRequest.
 * Use `create(CopyFileRequestSchema)` to create a new message.
 */
export declare const CopyFileRequestSchema: GenMessage<CopyFileRequest>;

/**
 * @generated from message nimbus_public.v1.CopyFileResponse
 */
export declare type CopyFileResponse = Message<"nimbus_public.v1.CopyFileResponse"> & {
  /**
   * @generated from field: repeated string object_ids = 1;
   */
  objectIds: string[];
};

/**
 * Describes the message nimbus_public.v1.CopyFileResponse.
 * Use `create(CopyFileResponseSchema)` to create a new message.
 */
export declare const CopyFileResponseSchema: GenMessage<CopyFileResponse>;

/**
 * Either a file or a directory.
 *
 * @generated from enum nimbus_public.v1.ObjectType
 */
export enum ObjectType {
  /**
   * @generated from enum value: OBJECT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: OBJECT_TYPE_FILE = 1;
   */
  FILE = 1,

  /**
   * @generated from enum value: OBJECT_TYPE_DIRECTORY = 2;
   */
  DIRECTORY = 2,
}

/**
 * Describes the enum nimbus_public.v1.ObjectType.
 */
export declare const ObjectTypeSchema: GenEnum<ObjectType>;

/**
 * Either Public or Private
 *
 * @generated from enum nimbus_public.v1.AccessType
 */
export enum AccessType {
  /**
   * @generated from enum value: ACCESS_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ACCESS_TYPE_PRIVATE = 1;
   */
  PRIVATE = 1,

  /**
   * @generated from enum value: ACCESS_TYPE_PUBLIC = 2;
   */
  PUBLIC = 2,
}

/**
 * Describes the enum nimbus_public.v1.AccessType.
 */
export declare const AccessTypeSchema: GenEnum<AccessType>;

/**
 * @generated from service nimbus_public.v1.NimbusPublicService
 */
export declare const NimbusPublicService: GenService<{
  /**
   * Upload the bytes.
   *
   * @generated from rpc nimbus_public.v1.NimbusPublicService.PutObject
   */
  putObject: {
    methodKind: "client_streaming";
    input: typeof PutObjectRequestSchema;
    output: typeof PutObjectResponseSchema;
  },
  /**
   * Read the bytes from the data.
   *
   * @generated from rpc nimbus_public.v1.NimbusPublicService.GetObject
   */
  getObject: {
    methodKind: "server_streaming";
    input: typeof GetObjectRequestSchema;
    output: typeof GetObjectResponseSchema;
  },
  /**
   * Delete an object.
   *
   * @generated from rpc nimbus_public.v1.NimbusPublicService.DeleteObject
   */
  deleteObject: {
    methodKind: "unary";
    input: typeof DeleteObjectRequestSchema;
    output: typeof DeleteObjectResponseSchema;
  },
  /**
   * Update the access type of the object PUBLIC/PRIVATE.
   *
   * @generated from rpc nimbus_public.v1.NimbusPublicService.UpdateAccessType
   */
  updateAccessType: {
    methodKind: "unary";
    input: typeof UpdateAccessTypeRequestSchema;
    output: typeof UpdateAccessTypeResponseSchema;
  },
  /**
   * If a valid directory found then returns it objects.
   *
   * @generated from rpc nimbus_public.v1.NimbusPublicService.GetDirectoryContent
   */
  getDirectoryContent: {
    methodKind: "unary";
    input: typeof GetDirectoryContentRequestSchema;
    output: typeof GetDirectoryContentResponseSchema;
  },
  /**
   * The file id looks like files/names.txt
   *
   * @generated from rpc nimbus_public.v1.NimbusPublicService.FindObjectById
   */
  findObjectById: {
    methodKind: "unary";
    input: typeof FindObjectByIdRequestSchema;
    output: typeof FindObjectByIdResponseSchema;
  },
  /**
   * Update the move, replace if file already exist.
   *
   * @generated from rpc nimbus_public.v1.NimbusPublicService.RenameFile
   */
  renameFile: {
    methodKind: "unary";
    input: typeof RenameFileRequestSchema;
    output: typeof RenameFileResponseSchema;
  },
  /**
   * Copy the file to another location.
   *
   * @generated from rpc nimbus_public.v1.NimbusPublicService.CopyFile
   */
  copyFile: {
    methodKind: "unary";
    input: typeof CopyFileRequestSchema;
    output: typeof CopyFileResponseSchema;
  },
}>;

