// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nimbus_public/v1/nimbus_public_service.proto

package public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateAccessTypeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObjectAccessInfo []*ObjectAccessInfo    `protobuf:"bytes,1,rep,name=object_access_info,json=objectAccessInfo,proto3" json:"object_access_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateAccessTypeRequest) Reset() {
	*x = UpdateAccessTypeRequest{}
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccessTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccessTypeRequest) ProtoMessage() {}

func (x *UpdateAccessTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccessTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccessTypeRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateAccessTypeRequest) GetObjectAccessInfo() []*ObjectAccessInfo {
	if x != nil {
		return x.ObjectAccessInfo
	}
	return nil
}

type UpdateAccessTypeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObjectAccessInfo []*ObjectAccessInfo    `protobuf:"bytes,1,rep,name=object_access_info,json=objectAccessInfo,proto3" json:"object_access_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateAccessTypeResponse) Reset() {
	*x = UpdateAccessTypeResponse{}
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccessTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccessTypeResponse) ProtoMessage() {}

func (x *UpdateAccessTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccessTypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccessTypeResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAccessTypeResponse) GetObjectAccessInfo() []*ObjectAccessInfo {
	if x != nil {
		return x.ObjectAccessInfo
	}
	return nil
}

type GetDirectoryContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	OffSet        string                 `protobuf:"bytes,2,opt,name=off_set,json=offSet,proto3" json:"off_set,omitempty"`
	Count         string                 `protobuf:"bytes,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryContentRequest) Reset() {
	*x = GetDirectoryContentRequest{}
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryContentRequest) ProtoMessage() {}

func (x *GetDirectoryContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryContentRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoryContentRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetDirectoryContentRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetDirectoryContentRequest) GetOffSet() string {
	if x != nil {
		return x.OffSet
	}
	return ""
}

func (x *GetDirectoryContentRequest) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

type GetDirectoryContentResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	ObjectCount   uint64                                    `protobuf:"varint,1,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`
	Objects       []*GetDirectoryContentResponse_ObjectInfo `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryContentResponse) Reset() {
	*x = GetDirectoryContentResponse{}
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryContentResponse) ProtoMessage() {}

func (x *GetDirectoryContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryContentResponse.ProtoReflect.Descriptor instead.
func (*GetDirectoryContentResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDirectoryContentResponse) GetObjectCount() uint64 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

func (x *GetDirectoryContentResponse) GetObjects() []*GetDirectoryContentResponse_ObjectInfo {
	if x != nil {
		return x.Objects
	}
	return nil
}

type FindObjectByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindObjectByNameRequest) Reset() {
	*x = FindObjectByNameRequest{}
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindObjectByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindObjectByNameRequest) ProtoMessage() {}

func (x *FindObjectByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindObjectByNameRequest.ProtoReflect.Descriptor instead.
func (*FindObjectByNameRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_service_proto_rawDescGZIP(), []int{4}
}

func (x *FindObjectByNameRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type FindObjectByNameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*FindObjectByNameResponse_Object
	//	*FindObjectByNameResponse_Error
	Data          isFindObjectByNameResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindObjectByNameResponse) Reset() {
	*x = FindObjectByNameResponse{}
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindObjectByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindObjectByNameResponse) ProtoMessage() {}

func (x *FindObjectByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindObjectByNameResponse.ProtoReflect.Descriptor instead.
func (*FindObjectByNameResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_service_proto_rawDescGZIP(), []int{5}
}

func (x *FindObjectByNameResponse) GetData() isFindObjectByNameResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FindObjectByNameResponse) GetObject() *ObjectDetails {
	if x != nil {
		if x, ok := x.Data.(*FindObjectByNameResponse_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *FindObjectByNameResponse) GetError() string {
	if x != nil {
		if x, ok := x.Data.(*FindObjectByNameResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isFindObjectByNameResponse_Data interface {
	isFindObjectByNameResponse_Data()
}

type FindObjectByNameResponse_Object struct {
	Object *ObjectDetails `protobuf:"bytes,1,opt,name=object,proto3,oneof"`
}

type FindObjectByNameResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*FindObjectByNameResponse_Object) isFindObjectByNameResponse_Data() {}

func (*FindObjectByNameResponse_Error) isFindObjectByNameResponse_Data() {}

type GetDirectoryContentResponse_ObjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	AccessType    AccessType             `protobuf:"varint,2,opt,name=access_type,json=accessType,proto3,enum=nimbus_public.v1.types.v1.AccessType" json:"access_type,omitempty"`
	ObjectType    ObjectType             `protobuf:"varint,3,opt,name=object_type,json=objectType,proto3,enum=nimbus_public.v1.types.v1.ObjectType" json:"object_type,omitempty"`
	CreatedOn     string                 `protobuf:"bytes,4,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryContentResponse_ObjectInfo) Reset() {
	*x = GetDirectoryContentResponse_ObjectInfo{}
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryContentResponse_ObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryContentResponse_ObjectInfo) ProtoMessage() {}

func (x *GetDirectoryContentResponse_ObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryContentResponse_ObjectInfo.ProtoReflect.Descriptor instead.
func (*GetDirectoryContentResponse_ObjectInfo) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetDirectoryContentResponse_ObjectInfo) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetDirectoryContentResponse_ObjectInfo) GetAccessType() AccessType {
	if x != nil {
		return x.AccessType
	}
	return AccessType_ACCESS_TYPE_UNSPECIFIED
}

func (x *GetDirectoryContentResponse_ObjectInfo) GetObjectType() ObjectType {
	if x != nil {
		return x.ObjectType
	}
	return ObjectType_OBJECT_TYPE_UNSPECIFIED
}

func (x *GetDirectoryContentResponse_ObjectInfo) GetCreatedOn() string {
	if x != nil {
		return x.CreatedOn
	}
	return ""
}

var File_nimbus_public_v1_nimbus_public_service_proto protoreflect.FileDescriptor

const file_nimbus_public_v1_nimbus_public_service_proto_rawDesc = "" +
	"\n" +
	",nimbus_public/v1/nimbus_public_service.proto\x12\x10nimbus_public.v1\x1a%nimbus_public/v1/types/v1/files.proto\"t\n" +
	"\x17UpdateAccessTypeRequest\x12Y\n" +
	"\x12object_access_info\x18\x01 \x03(\v2+.nimbus_public.v1.types.v1.ObjectAccessInfoR\x10objectAccessInfo\"u\n" +
	"\x18UpdateAccessTypeResponse\x12Y\n" +
	"\x12object_access_info\x18\x01 \x03(\v2+.nimbus_public.v1.types.v1.ObjectAccessInfoR\x10objectAccessInfo\"h\n" +
	"\x1aGetDirectoryContentRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12\x17\n" +
	"\aoff_set\x18\x02 \x01(\tR\x06offSet\x12\x14\n" +
	"\x05count\x18\x03 \x01(\tR\x05count\"\xef\x02\n" +
	"\x1bGetDirectoryContentResponse\x12!\n" +
	"\fobject_count\x18\x01 \x01(\x04R\vobjectCount\x12R\n" +
	"\aobjects\x18\x02 \x03(\v28.nimbus_public.v1.GetDirectoryContentResponse.ObjectInfoR\aobjects\x1a\xd8\x01\n" +
	"\n" +
	"ObjectInfo\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12F\n" +
	"\vaccess_type\x18\x02 \x01(\x0e2%.nimbus_public.v1.types.v1.AccessTypeR\n" +
	"accessType\x12F\n" +
	"\vobject_type\x18\x03 \x01(\x0e2%.nimbus_public.v1.types.v1.ObjectTypeR\n" +
	"objectType\x12\x1d\n" +
	"\n" +
	"created_on\x18\x04 \x01(\tR\tcreatedOn\"6\n" +
	"\x17FindObjectByNameRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"~\n" +
	"\x18FindObjectByNameResponse\x12B\n" +
	"\x06object\x18\x01 \x01(\v2(.nimbus_public.v1.types.v1.ObjectDetailsH\x00R\x06object\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\x06\n" +
	"\x04data2\xe1\x02\n" +
	"\x13NimbusPublicService\x12i\n" +
	"\x10UpdateAccessType\x12).nimbus_public.v1.UpdateAccessTypeRequest\x1a*.nimbus_public.v1.UpdateAccessTypeResponse\x12t\n" +
	"\x13GetDirectoryContent\x12,.nimbus_public.v1.GetDirectoryContentRequest\x1a-.nimbus_public.v1.GetDirectoryContentResponse0\x01\x12i\n" +
	"\x10FindObjectByName\x12).nimbus_public.v1.FindObjectByNameRequest\x1a*.nimbus_public.v1.FindObjectByNameResponseB\x9f\x01\n" +
	"\x14com.nimbus_public.v1B\x18NimbusPublicServiceProtoP\x01Z\x10proto-gen/public\xa2\x02\x03NXX\xaa\x02\x0fNimbusPublic.V1\xca\x02\x0fNimbusPublic\\V1\xe2\x02\x1bNimbusPublic\\V1\\GPBMetadata\xea\x02\x10NimbusPublic::V1b\x06proto3"

var (
	file_nimbus_public_v1_nimbus_public_service_proto_rawDescOnce sync.Once
	file_nimbus_public_v1_nimbus_public_service_proto_rawDescData []byte
)

func file_nimbus_public_v1_nimbus_public_service_proto_rawDescGZIP() []byte {
	file_nimbus_public_v1_nimbus_public_service_proto_rawDescOnce.Do(func() {
		file_nimbus_public_v1_nimbus_public_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nimbus_public_v1_nimbus_public_service_proto_rawDesc), len(file_nimbus_public_v1_nimbus_public_service_proto_rawDesc)))
	})
	return file_nimbus_public_v1_nimbus_public_service_proto_rawDescData
}

var file_nimbus_public_v1_nimbus_public_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_nimbus_public_v1_nimbus_public_service_proto_goTypes = []any{
	(*UpdateAccessTypeRequest)(nil),                // 0: nimbus_public.v1.UpdateAccessTypeRequest
	(*UpdateAccessTypeResponse)(nil),               // 1: nimbus_public.v1.UpdateAccessTypeResponse
	(*GetDirectoryContentRequest)(nil),             // 2: nimbus_public.v1.GetDirectoryContentRequest
	(*GetDirectoryContentResponse)(nil),            // 3: nimbus_public.v1.GetDirectoryContentResponse
	(*FindObjectByNameRequest)(nil),                // 4: nimbus_public.v1.FindObjectByNameRequest
	(*FindObjectByNameResponse)(nil),               // 5: nimbus_public.v1.FindObjectByNameResponse
	(*GetDirectoryContentResponse_ObjectInfo)(nil), // 6: nimbus_public.v1.GetDirectoryContentResponse.ObjectInfo
	(*ObjectAccessInfo)(nil),                       // 7: nimbus_public.v1.types.v1.ObjectAccessInfo
	(*ObjectDetails)(nil),                          // 8: nimbus_public.v1.types.v1.ObjectDetails
	(AccessType)(0),                                // 9: nimbus_public.v1.types.v1.AccessType
	(ObjectType)(0),                                // 10: nimbus_public.v1.types.v1.ObjectType
}
var file_nimbus_public_v1_nimbus_public_service_proto_depIdxs = []int32{
	7,  // 0: nimbus_public.v1.UpdateAccessTypeRequest.object_access_info:type_name -> nimbus_public.v1.types.v1.ObjectAccessInfo
	7,  // 1: nimbus_public.v1.UpdateAccessTypeResponse.object_access_info:type_name -> nimbus_public.v1.types.v1.ObjectAccessInfo
	6,  // 2: nimbus_public.v1.GetDirectoryContentResponse.objects:type_name -> nimbus_public.v1.GetDirectoryContentResponse.ObjectInfo
	8,  // 3: nimbus_public.v1.FindObjectByNameResponse.object:type_name -> nimbus_public.v1.types.v1.ObjectDetails
	9,  // 4: nimbus_public.v1.GetDirectoryContentResponse.ObjectInfo.access_type:type_name -> nimbus_public.v1.types.v1.AccessType
	10, // 5: nimbus_public.v1.GetDirectoryContentResponse.ObjectInfo.object_type:type_name -> nimbus_public.v1.types.v1.ObjectType
	0,  // 6: nimbus_public.v1.NimbusPublicService.UpdateAccessType:input_type -> nimbus_public.v1.UpdateAccessTypeRequest
	2,  // 7: nimbus_public.v1.NimbusPublicService.GetDirectoryContent:input_type -> nimbus_public.v1.GetDirectoryContentRequest
	4,  // 8: nimbus_public.v1.NimbusPublicService.FindObjectByName:input_type -> nimbus_public.v1.FindObjectByNameRequest
	1,  // 9: nimbus_public.v1.NimbusPublicService.UpdateAccessType:output_type -> nimbus_public.v1.UpdateAccessTypeResponse
	3,  // 10: nimbus_public.v1.NimbusPublicService.GetDirectoryContent:output_type -> nimbus_public.v1.GetDirectoryContentResponse
	5,  // 11: nimbus_public.v1.NimbusPublicService.FindObjectByName:output_type -> nimbus_public.v1.FindObjectByNameResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_nimbus_public_v1_nimbus_public_service_proto_init() }
func file_nimbus_public_v1_nimbus_public_service_proto_init() {
	if File_nimbus_public_v1_nimbus_public_service_proto != nil {
		return
	}
	file_nimbus_public_v1_types_v1_files_proto_init()
	file_nimbus_public_v1_nimbus_public_service_proto_msgTypes[5].OneofWrappers = []any{
		(*FindObjectByNameResponse_Object)(nil),
		(*FindObjectByNameResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nimbus_public_v1_nimbus_public_service_proto_rawDesc), len(file_nimbus_public_v1_nimbus_public_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nimbus_public_v1_nimbus_public_service_proto_goTypes,
		DependencyIndexes: file_nimbus_public_v1_nimbus_public_service_proto_depIdxs,
		MessageInfos:      file_nimbus_public_v1_nimbus_public_service_proto_msgTypes,
	}.Build()
	File_nimbus_public_v1_nimbus_public_service_proto = out.File
	file_nimbus_public_v1_nimbus_public_service_proto_goTypes = nil
	file_nimbus_public_v1_nimbus_public_service_proto_depIdxs = nil
}
