// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nimbus_public/v1/nimbus_public_object_service.proto

package public

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NimbusPublicObjectService_CreateOrUpdateObject_FullMethodName = "/nimbus_public.v1.NimbusPublicObjectService/CreateOrUpdateObject"
	NimbusPublicObjectService_GetObject_FullMethodName            = "/nimbus_public.v1.NimbusPublicObjectService/GetObject"
	NimbusPublicObjectService_DeleteObject_FullMethodName         = "/nimbus_public.v1.NimbusPublicObjectService/DeleteObject"
)

// NimbusPublicObjectServiceClient is the client API for NimbusPublicObjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This service is only to used to send and recive the raw data bytes.
type NimbusPublicObjectServiceClient interface {
	// Upload the bytes.
	CreateOrUpdateObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse], error)
	// Read the bytes from the data.
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectResponse], error)
	// Delete an object.
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
}

type nimbusPublicObjectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNimbusPublicObjectServiceClient(cc grpc.ClientConnInterface) NimbusPublicObjectServiceClient {
	return &nimbusPublicObjectServiceClient{cc}
}

func (c *nimbusPublicObjectServiceClient) CreateOrUpdateObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NimbusPublicObjectService_ServiceDesc.Streams[0], NimbusPublicObjectService_CreateOrUpdateObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusPublicObjectService_CreateOrUpdateObjectClient = grpc.ClientStreamingClient[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]

func (c *nimbusPublicObjectServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NimbusPublicObjectService_ServiceDesc.Streams[1], NimbusPublicObjectService_GetObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetObjectRequest, GetObjectResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusPublicObjectService_GetObjectClient = grpc.ServerStreamingClient[GetObjectResponse]

func (c *nimbusPublicObjectServiceClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, NimbusPublicObjectService_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NimbusPublicObjectServiceServer is the server API for NimbusPublicObjectService service.
// All implementations must embed UnimplementedNimbusPublicObjectServiceServer
// for forward compatibility.
//
// This service is only to used to send and recive the raw data bytes.
type NimbusPublicObjectServiceServer interface {
	// Upload the bytes.
	CreateOrUpdateObject(grpc.ClientStreamingServer[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]) error
	// Read the bytes from the data.
	GetObject(*GetObjectRequest, grpc.ServerStreamingServer[GetObjectResponse]) error
	// Delete an object.
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	mustEmbedUnimplementedNimbusPublicObjectServiceServer()
}

// UnimplementedNimbusPublicObjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNimbusPublicObjectServiceServer struct{}

func (UnimplementedNimbusPublicObjectServiceServer) CreateOrUpdateObject(grpc.ClientStreamingServer[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateOrUpdateObject not implemented")
}
func (UnimplementedNimbusPublicObjectServiceServer) GetObject(*GetObjectRequest, grpc.ServerStreamingServer[GetObjectResponse]) error {
	return status.Error(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedNimbusPublicObjectServiceServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedNimbusPublicObjectServiceServer) mustEmbedUnimplementedNimbusPublicObjectServiceServer() {
}
func (UnimplementedNimbusPublicObjectServiceServer) testEmbeddedByValue() {}

// UnsafeNimbusPublicObjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NimbusPublicObjectServiceServer will
// result in compilation errors.
type UnsafeNimbusPublicObjectServiceServer interface {
	mustEmbedUnimplementedNimbusPublicObjectServiceServer()
}

func RegisterNimbusPublicObjectServiceServer(s grpc.ServiceRegistrar, srv NimbusPublicObjectServiceServer) {
	// If the following call panics, it indicates UnimplementedNimbusPublicObjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NimbusPublicObjectService_ServiceDesc, srv)
}

func _NimbusPublicObjectService_CreateOrUpdateObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NimbusPublicObjectServiceServer).CreateOrUpdateObject(&grpc.GenericServerStream[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusPublicObjectService_CreateOrUpdateObjectServer = grpc.ClientStreamingServer[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]

func _NimbusPublicObjectService_GetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NimbusPublicObjectServiceServer).GetObject(m, &grpc.GenericServerStream[GetObjectRequest, GetObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusPublicObjectService_GetObjectServer = grpc.ServerStreamingServer[GetObjectResponse]

func _NimbusPublicObjectService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NimbusPublicObjectServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NimbusPublicObjectService_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NimbusPublicObjectServiceServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NimbusPublicObjectService_ServiceDesc is the grpc.ServiceDesc for NimbusPublicObjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NimbusPublicObjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nimbus_public.v1.NimbusPublicObjectService",
	HandlerType: (*NimbusPublicObjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteObject",
			Handler:    _NimbusPublicObjectService_DeleteObject_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateOrUpdateObject",
			Handler:       _NimbusPublicObjectService_CreateOrUpdateObject_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetObject",
			Handler:       _NimbusPublicObjectService_GetObject_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nimbus_public/v1/nimbus_public_object_service.proto",
}
