// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nimbus_public/v1/nimbus_public_object_service.proto

package public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stream of bytes of the file.
type CreateOrUpdateObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateObjectRequest) Reset() {
	*x = CreateOrUpdateObjectRequest{}
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateObjectRequest) ProtoMessage() {}

func (x *CreateOrUpdateObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateObjectRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateObjectRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrUpdateObjectRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// After sending the bytes either getting the object response or the error message from the server.
type CreateOrUpdateObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*CreateOrUpdateObjectResponse_ErrorMessage
	//	*CreateOrUpdateObjectResponse_ObjectDetails
	Response      isCreateOrUpdateObjectResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateObjectResponse) Reset() {
	*x = CreateOrUpdateObjectResponse{}
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateObjectResponse) ProtoMessage() {}

func (x *CreateOrUpdateObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateObjectResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateObjectResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrUpdateObjectResponse) GetResponse() isCreateOrUpdateObjectResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateOrUpdateObjectResponse) GetErrorMessage() string {
	if x != nil {
		if x, ok := x.Response.(*CreateOrUpdateObjectResponse_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return ""
}

func (x *CreateOrUpdateObjectResponse) GetObjectDetails() *ObjectDetails {
	if x != nil {
		if x, ok := x.Response.(*CreateOrUpdateObjectResponse_ObjectDetails); ok {
			return x.ObjectDetails
		}
	}
	return nil
}

type isCreateOrUpdateObjectResponse_Response interface {
	isCreateOrUpdateObjectResponse_Response()
}

type CreateOrUpdateObjectResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

type CreateOrUpdateObjectResponse_ObjectDetails struct {
	ObjectDetails *ObjectDetails `protobuf:"bytes,3,opt,name=object_details,json=objectDetails,proto3,oneof"`
}

func (*CreateOrUpdateObjectResponse_ErrorMessage) isCreateOrUpdateObjectResponse_Response() {}

func (*CreateOrUpdateObjectResponse_ObjectDetails) isCreateOrUpdateObjectResponse_Response() {}

// Object id is like the file id, this id must be a file path not a directory or invalid file name.
type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

// The stream of bytes of the file.
type GetObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetObjectResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectIds     []string               `protobuf:"bytes,1,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectRequest) Reset() {
	*x = DeleteObjectRequest{}
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectRequest) ProtoMessage() {}

func (x *DeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteObjectRequest) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

type DeleteObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectIds     []string               `protobuf:"bytes,1,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectResponse) Reset() {
	*x = DeleteObjectResponse{}
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectResponse) ProtoMessage() {}

func (x *DeleteObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteObjectResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteObjectResponse) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

var File_nimbus_public_v1_nimbus_public_object_service_proto protoreflect.FileDescriptor

const file_nimbus_public_v1_nimbus_public_object_service_proto_rawDesc = "" +
	"\n" +
	"3nimbus_public/v1/nimbus_public_object_service.proto\x12\x10nimbus_public.v1\x1a%nimbus_public/v1/types/v1/files.proto\"1\n" +
	"\x1bCreateOrUpdateObjectRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xa4\x01\n" +
	"\x1cCreateOrUpdateObjectResponse\x12%\n" +
	"\rerror_message\x18\x02 \x01(\tH\x00R\ferrorMessage\x12Q\n" +
	"\x0eobject_details\x18\x03 \x01(\v2(.nimbus_public.v1.types.v1.ObjectDetailsH\x00R\robjectDetailsB\n" +
	"\n" +
	"\bresponse\"/\n" +
	"\x10GetObjectRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"'\n" +
	"\x11GetObjectResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"4\n" +
	"\x13DeleteObjectRequest\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x01 \x03(\tR\tobjectIds\"5\n" +
	"\x14DeleteObjectResponse\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x01 \x03(\tR\tobjectIds2\xcb\x02\n" +
	"\x19NimbusPublicObjectService\x12w\n" +
	"\x14CreateOrUpdateObject\x12-.nimbus_public.v1.CreateOrUpdateObjectRequest\x1a..nimbus_public.v1.CreateOrUpdateObjectResponse(\x01\x12V\n" +
	"\tGetObject\x12\".nimbus_public.v1.GetObjectRequest\x1a#.nimbus_public.v1.GetObjectResponse0\x01\x12]\n" +
	"\fDeleteObject\x12%.nimbus_public.v1.DeleteObjectRequest\x1a&.nimbus_public.v1.DeleteObjectResponseB\xa5\x01\n" +
	"\x14com.nimbus_public.v1B\x1eNimbusPublicObjectServiceProtoP\x01Z\x10proto-gen/public\xa2\x02\x03NXX\xaa\x02\x0fNimbusPublic.V1\xca\x02\x0fNimbusPublic\\V1\xe2\x02\x1bNimbusPublic\\V1\\GPBMetadata\xea\x02\x10NimbusPublic::V1b\x06proto3"

var (
	file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescOnce sync.Once
	file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescData []byte
)

func file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescGZIP() []byte {
	file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescOnce.Do(func() {
		file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nimbus_public_v1_nimbus_public_object_service_proto_rawDesc), len(file_nimbus_public_v1_nimbus_public_object_service_proto_rawDesc)))
	})
	return file_nimbus_public_v1_nimbus_public_object_service_proto_rawDescData
}

var file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nimbus_public_v1_nimbus_public_object_service_proto_goTypes = []any{
	(*CreateOrUpdateObjectRequest)(nil),  // 0: nimbus_public.v1.CreateOrUpdateObjectRequest
	(*CreateOrUpdateObjectResponse)(nil), // 1: nimbus_public.v1.CreateOrUpdateObjectResponse
	(*GetObjectRequest)(nil),             // 2: nimbus_public.v1.GetObjectRequest
	(*GetObjectResponse)(nil),            // 3: nimbus_public.v1.GetObjectResponse
	(*DeleteObjectRequest)(nil),          // 4: nimbus_public.v1.DeleteObjectRequest
	(*DeleteObjectResponse)(nil),         // 5: nimbus_public.v1.DeleteObjectResponse
	(*ObjectDetails)(nil),                // 6: nimbus_public.v1.types.v1.ObjectDetails
}
var file_nimbus_public_v1_nimbus_public_object_service_proto_depIdxs = []int32{
	6, // 0: nimbus_public.v1.CreateOrUpdateObjectResponse.object_details:type_name -> nimbus_public.v1.types.v1.ObjectDetails
	0, // 1: nimbus_public.v1.NimbusPublicObjectService.CreateOrUpdateObject:input_type -> nimbus_public.v1.CreateOrUpdateObjectRequest
	2, // 2: nimbus_public.v1.NimbusPublicObjectService.GetObject:input_type -> nimbus_public.v1.GetObjectRequest
	4, // 3: nimbus_public.v1.NimbusPublicObjectService.DeleteObject:input_type -> nimbus_public.v1.DeleteObjectRequest
	1, // 4: nimbus_public.v1.NimbusPublicObjectService.CreateOrUpdateObject:output_type -> nimbus_public.v1.CreateOrUpdateObjectResponse
	3, // 5: nimbus_public.v1.NimbusPublicObjectService.GetObject:output_type -> nimbus_public.v1.GetObjectResponse
	5, // 6: nimbus_public.v1.NimbusPublicObjectService.DeleteObject:output_type -> nimbus_public.v1.DeleteObjectResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nimbus_public_v1_nimbus_public_object_service_proto_init() }
func file_nimbus_public_v1_nimbus_public_object_service_proto_init() {
	if File_nimbus_public_v1_nimbus_public_object_service_proto != nil {
		return
	}
	file_nimbus_public_v1_types_v1_files_proto_init()
	file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes[1].OneofWrappers = []any{
		(*CreateOrUpdateObjectResponse_ErrorMessage)(nil),
		(*CreateOrUpdateObjectResponse_ObjectDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nimbus_public_v1_nimbus_public_object_service_proto_rawDesc), len(file_nimbus_public_v1_nimbus_public_object_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nimbus_public_v1_nimbus_public_object_service_proto_goTypes,
		DependencyIndexes: file_nimbus_public_v1_nimbus_public_object_service_proto_depIdxs,
		MessageInfos:      file_nimbus_public_v1_nimbus_public_object_service_proto_msgTypes,
	}.Build()
	File_nimbus_public_v1_nimbus_public_object_service_proto = out.File
	file_nimbus_public_v1_nimbus_public_object_service_proto_goTypes = nil
	file_nimbus_public_v1_nimbus_public_object_service_proto_depIdxs = nil
}
