// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nimbus_public/v1/nimbus_public_service.proto

package public

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NimbusPublicService_UpdateAccessType_FullMethodName    = "/nimbus_public.v1.NimbusPublicService/UpdateAccessType"
	NimbusPublicService_GetDirectoryContent_FullMethodName = "/nimbus_public.v1.NimbusPublicService/GetDirectoryContent"
	NimbusPublicService_FindObjectByName_FullMethodName    = "/nimbus_public.v1.NimbusPublicService/FindObjectByName"
)

// NimbusPublicServiceClient is the client API for NimbusPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NimbusPublicServiceClient interface {
	// Update the access type of the object PUBLIC/PRIVATE.
	UpdateAccessType(ctx context.Context, in *UpdateAccessTypeRequest, opts ...grpc.CallOption) (*UpdateAccessTypeResponse, error)
	// If a valid directory found then returns it objects.
	GetDirectoryContent(ctx context.Context, in *GetDirectoryContentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDirectoryContentResponse], error)
	FindObjectByName(ctx context.Context, in *FindObjectByNameRequest, opts ...grpc.CallOption) (*FindObjectByNameResponse, error)
}

type nimbusPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNimbusPublicServiceClient(cc grpc.ClientConnInterface) NimbusPublicServiceClient {
	return &nimbusPublicServiceClient{cc}
}

func (c *nimbusPublicServiceClient) UpdateAccessType(ctx context.Context, in *UpdateAccessTypeRequest, opts ...grpc.CallOption) (*UpdateAccessTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAccessTypeResponse)
	err := c.cc.Invoke(ctx, NimbusPublicService_UpdateAccessType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nimbusPublicServiceClient) GetDirectoryContent(ctx context.Context, in *GetDirectoryContentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDirectoryContentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NimbusPublicService_ServiceDesc.Streams[0], NimbusPublicService_GetDirectoryContent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDirectoryContentRequest, GetDirectoryContentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusPublicService_GetDirectoryContentClient = grpc.ServerStreamingClient[GetDirectoryContentResponse]

func (c *nimbusPublicServiceClient) FindObjectByName(ctx context.Context, in *FindObjectByNameRequest, opts ...grpc.CallOption) (*FindObjectByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindObjectByNameResponse)
	err := c.cc.Invoke(ctx, NimbusPublicService_FindObjectByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NimbusPublicServiceServer is the server API for NimbusPublicService service.
// All implementations must embed UnimplementedNimbusPublicServiceServer
// for forward compatibility.
type NimbusPublicServiceServer interface {
	// Update the access type of the object PUBLIC/PRIVATE.
	UpdateAccessType(context.Context, *UpdateAccessTypeRequest) (*UpdateAccessTypeResponse, error)
	// If a valid directory found then returns it objects.
	GetDirectoryContent(*GetDirectoryContentRequest, grpc.ServerStreamingServer[GetDirectoryContentResponse]) error
	FindObjectByName(context.Context, *FindObjectByNameRequest) (*FindObjectByNameResponse, error)
	mustEmbedUnimplementedNimbusPublicServiceServer()
}

// UnimplementedNimbusPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNimbusPublicServiceServer struct{}

func (UnimplementedNimbusPublicServiceServer) UpdateAccessType(context.Context, *UpdateAccessTypeRequest) (*UpdateAccessTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAccessType not implemented")
}
func (UnimplementedNimbusPublicServiceServer) GetDirectoryContent(*GetDirectoryContentRequest, grpc.ServerStreamingServer[GetDirectoryContentResponse]) error {
	return status.Error(codes.Unimplemented, "method GetDirectoryContent not implemented")
}
func (UnimplementedNimbusPublicServiceServer) FindObjectByName(context.Context, *FindObjectByNameRequest) (*FindObjectByNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindObjectByName not implemented")
}
func (UnimplementedNimbusPublicServiceServer) mustEmbedUnimplementedNimbusPublicServiceServer() {}
func (UnimplementedNimbusPublicServiceServer) testEmbeddedByValue()                             {}

// UnsafeNimbusPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NimbusPublicServiceServer will
// result in compilation errors.
type UnsafeNimbusPublicServiceServer interface {
	mustEmbedUnimplementedNimbusPublicServiceServer()
}

func RegisterNimbusPublicServiceServer(s grpc.ServiceRegistrar, srv NimbusPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedNimbusPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NimbusPublicService_ServiceDesc, srv)
}

func _NimbusPublicService_UpdateAccessType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccessTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NimbusPublicServiceServer).UpdateAccessType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NimbusPublicService_UpdateAccessType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NimbusPublicServiceServer).UpdateAccessType(ctx, req.(*UpdateAccessTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NimbusPublicService_GetDirectoryContent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDirectoryContentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NimbusPublicServiceServer).GetDirectoryContent(m, &grpc.GenericServerStream[GetDirectoryContentRequest, GetDirectoryContentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusPublicService_GetDirectoryContentServer = grpc.ServerStreamingServer[GetDirectoryContentResponse]

func _NimbusPublicService_FindObjectByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindObjectByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NimbusPublicServiceServer).FindObjectByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NimbusPublicService_FindObjectByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NimbusPublicServiceServer).FindObjectByName(ctx, req.(*FindObjectByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NimbusPublicService_ServiceDesc is the grpc.ServiceDesc for NimbusPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NimbusPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nimbus_public.v1.NimbusPublicService",
	HandlerType: (*NimbusPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAccessType",
			Handler:    _NimbusPublicService_UpdateAccessType_Handler,
		},
		{
			MethodName: "FindObjectByName",
			Handler:    _NimbusPublicService_FindObjectByName_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDirectoryContent",
			Handler:       _NimbusPublicService_GetDirectoryContent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nimbus_public/v1/nimbus_public_service.proto",
}
