services:
  postgres:
    image: postgres:alpine3.24
    container_name: nimbus_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
  scylla:
    image: scylladb/scylla:2025.1
    container_name: nimbus_scylla
    ports:
      - "9042:9042"


