// @generated
// This file is @generated by prost-build.
/// Stream of bytes of the file.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateOrUpdateObjectRequest {
    #[prost(bytes="vec", tag="1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// After sending the bytes either getting the object response or the error message from the server.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateOrUpdateObjectResponse {
    #[prost(oneof="create_or_update_object_response::Response", tags="2, 3")]
    pub response: ::core::option::Option<create_or_update_object_response::Response>,
}
/// Nested message and enum types in `CreateOrUpdateObjectResponse`.
pub mod create_or_update_object_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Response {
        #[prost(string, tag="2")]
        ErrorMessage(::prost::alloc::string::String),
        #[prost(message, tag="3")]
        ObjectDetails(super::types::v1::ObjectDetails),
    }
}
/// Object id is like the file id, this id must be a file path not a directory or invalid file name.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetObjectRequest {
    #[prost(string, tag="1")]
    pub object_id: ::prost::alloc::string::String,
}
/// The stream of bytes of the file.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetObjectResponse {
    #[prost(bytes="vec", tag="1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Status represents the status of an operation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Status {
    Unspecified = 0,
    Failed = 1,
    Success = 2,
}
impl Status {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STATUS_UNSPECIFIED",
            Self::Failed => "STATUS_FAILED",
            Self::Success => "STATUS_SUCCESS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "STATUS_FAILED" => Some(Self::Failed),
            "STATUS_SUCCESS" => Some(Self::Success),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteObjectRequest {
    #[prost(string, repeated, tag="1")]
    pub object_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteObjectResponse {
    #[prost(string, repeated, tag="1")]
    pub object_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateAccessTypeRequest {
    #[prost(message, repeated, tag="1")]
    pub object_access_info: ::prost::alloc::vec::Vec<types::v1::ObjectAccessInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateAccessTypeResponse {
    #[prost(message, repeated, tag="1")]
    pub object_access_info: ::prost::alloc::vec::Vec<types::v1::ObjectAccessInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDirectoryContentRequest {
    #[prost(string, tag="1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub off_set: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub count: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDirectoryContentResponse {
    #[prost(uint64, tag="1")]
    pub object_count: u64,
    #[prost(message, repeated, tag="2")]
    pub objects: ::prost::alloc::vec::Vec<get_directory_content_response::ObjectInfo>,
}
/// Nested message and enum types in `GetDirectoryContentResponse`.
pub mod get_directory_content_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ObjectInfo {
        #[prost(string, tag="1")]
        pub object_id: ::prost::alloc::string::String,
        #[prost(enumeration="super::types::v1::AccessType", tag="2")]
        pub access_type: i32,
        #[prost(enumeration="super::types::v1::ObjectType", tag="3")]
        pub object_type: i32,
        #[prost(string, tag="4")]
        pub created_on: ::prost::alloc::string::String,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FindObjectByNameRequest {
    #[prost(string, tag="1")]
    pub object_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FindObjectByNameResponse {
    #[prost(oneof="find_object_by_name_response::Data", tags="1, 2")]
    pub data: ::core::option::Option<find_object_by_name_response::Data>,
}
/// Nested message and enum types in `FindObjectByNameResponse`.
pub mod find_object_by_name_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag="1")]
        Object(super::types::v1::ObjectDetails),
        #[prost(string, tag="2")]
        Error(::prost::alloc::string::String),
    }
}
include!("nimbus.v1.tonic.rs");
// @@protoc_insertion_point(module)