// @generated
// This file is @generated by prost-build.
/// The access information of an object it can be used via public url or only access using personal access token.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObjectAccessInfo {
    #[prost(string, tag="1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(enumeration="AccessType", tag="2")]
    pub access_type: i32,
}
/// The details of any object it can be file or a directory and the access url if the object is public otherwise it can be only access via personal access token.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObjectDetails {
    #[prost(enumeration="ObjectType", tag="1")]
    pub object_type: i32,
    #[prost(string, tag="2")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub object_size: u64,
    #[prost(enumeration="AccessType", tag="4")]
    pub access_type: i32,
    #[prost(string, tag="5")]
    pub created_on: ::prost::alloc::string::String,
    /// The access url of a directory is referd as static directory which serve static contents.
    #[prost(string, optional, tag="6")]
    pub access_url: ::core::option::Option<::prost::alloc::string::String>,
}
/// Either a file or a directory.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ObjectType {
    Unspecified = 0,
    File = 1,
    Directory = 2,
}
impl ObjectType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OBJECT_TYPE_UNSPECIFIED",
            Self::File => "OBJECT_TYPE_FILE",
            Self::Directory => "OBJECT_TYPE_DIRECTORY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OBJECT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "OBJECT_TYPE_FILE" => Some(Self::File),
            "OBJECT_TYPE_DIRECTORY" => Some(Self::Directory),
            _ => None,
        }
    }
}
/// Either Public or Private
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AccessType {
    Unspecified = 0,
    Private = 1,
    Public = 2,
}
impl AccessType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ACCESS_TYPE_UNSPECIFIED",
            Self::Private => "ACCESS_TYPE_PRIVATE",
            Self::Public => "ACCESS_TYPE_PUBLIC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACCESS_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "ACCESS_TYPE_PRIVATE" => Some(Self::Private),
            "ACCESS_TYPE_PUBLIC" => Some(Self::Public),
            _ => None,
        }
    }
}
/// The authorization sent over the header to access the Objects.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Authorization {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
