// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nimbus/v1/nimbus_object_service.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the status of an operation.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_FAILED      Status = 1
	Status_STATUS_SUCCESS     Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_FAILED",
		2: "STATUS_SUCCESS",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_FAILED":      1,
		"STATUS_SUCCESS":     2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_nimbus_v1_nimbus_object_service_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_nimbus_v1_nimbus_object_service_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_nimbus_v1_nimbus_object_service_proto_rawDescGZIP(), []int{0}
}

// Stream of bytes of the file.
type CreateOrUpdateObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateObjectRequest) Reset() {
	*x = CreateOrUpdateObjectRequest{}
	mi := &file_nimbus_v1_nimbus_object_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateObjectRequest) ProtoMessage() {}

func (x *CreateOrUpdateObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_v1_nimbus_object_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateObjectRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateObjectRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_v1_nimbus_object_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrUpdateObjectRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// After sending the bytes either getting the object response or the error message from the server.
type CreateOrUpdateObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*CreateOrUpdateObjectResponse_ErrorMessage
	//	*CreateOrUpdateObjectResponse_ObjectDetails
	Response      isCreateOrUpdateObjectResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateObjectResponse) Reset() {
	*x = CreateOrUpdateObjectResponse{}
	mi := &file_nimbus_v1_nimbus_object_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateObjectResponse) ProtoMessage() {}

func (x *CreateOrUpdateObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_v1_nimbus_object_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateObjectResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateObjectResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_v1_nimbus_object_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrUpdateObjectResponse) GetResponse() isCreateOrUpdateObjectResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateOrUpdateObjectResponse) GetErrorMessage() string {
	if x != nil {
		if x, ok := x.Response.(*CreateOrUpdateObjectResponse_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return ""
}

func (x *CreateOrUpdateObjectResponse) GetObjectDetails() *ObjectDetails {
	if x != nil {
		if x, ok := x.Response.(*CreateOrUpdateObjectResponse_ObjectDetails); ok {
			return x.ObjectDetails
		}
	}
	return nil
}

type isCreateOrUpdateObjectResponse_Response interface {
	isCreateOrUpdateObjectResponse_Response()
}

type CreateOrUpdateObjectResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

type CreateOrUpdateObjectResponse_ObjectDetails struct {
	ObjectDetails *ObjectDetails `protobuf:"bytes,3,opt,name=object_details,json=objectDetails,proto3,oneof"`
}

func (*CreateOrUpdateObjectResponse_ErrorMessage) isCreateOrUpdateObjectResponse_Response() {}

func (*CreateOrUpdateObjectResponse_ObjectDetails) isCreateOrUpdateObjectResponse_Response() {}

// Object id is like the file id, this id must be a file path not a directory or invalid file name.
type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_nimbus_v1_nimbus_object_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_v1_nimbus_object_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_v1_nimbus_object_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

// The stream of bytes of the file.
type GetObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_nimbus_v1_nimbus_object_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_v1_nimbus_object_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_v1_nimbus_object_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetObjectResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_nimbus_v1_nimbus_object_service_proto protoreflect.FileDescriptor

const file_nimbus_v1_nimbus_object_service_proto_rawDesc = "" +
	"\n" +
	"%nimbus/v1/nimbus_object_service.proto\x12\tnimbus.v1\x1a\x1enimbus/v1/types/v1/files.proto\"1\n" +
	"\x1bCreateOrUpdateObjectRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x9d\x01\n" +
	"\x1cCreateOrUpdateObjectResponse\x12%\n" +
	"\rerror_message\x18\x02 \x01(\tH\x00R\ferrorMessage\x12J\n" +
	"\x0eobject_details\x18\x03 \x01(\v2!.nimbus.v1.types.v1.ObjectDetailsH\x00R\robjectDetailsB\n" +
	"\n" +
	"\bresponse\"/\n" +
	"\x10GetObjectRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"'\n" +
	"\x11GetObjectResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*G\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x01\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x022\xca\x01\n" +
	"\x13NimbusObjectService\x12i\n" +
	"\x14CreateOrUpdateObject\x12&.nimbus.v1.CreateOrUpdateObjectRequest\x1a'.nimbus.v1.CreateOrUpdateObjectResponse(\x01\x12H\n" +
	"\tGetObject\x12\x1b.nimbus.v1.GetObjectRequest\x1a\x1c.nimbus.v1.GetObjectResponse0\x01B\x80\x01\n" +
	"\rcom.nimbus.v1B\x18NimbusObjectServiceProtoP\x01Z\x10proto-gen/client\xa2\x02\x03NXX\xaa\x02\tNimbus.V1\xca\x02\tNimbus\\V1\xe2\x02\x15Nimbus\\V1\\GPBMetadata\xea\x02\n" +
	"Nimbus::V1b\x06proto3"

var (
	file_nimbus_v1_nimbus_object_service_proto_rawDescOnce sync.Once
	file_nimbus_v1_nimbus_object_service_proto_rawDescData []byte
)

func file_nimbus_v1_nimbus_object_service_proto_rawDescGZIP() []byte {
	file_nimbus_v1_nimbus_object_service_proto_rawDescOnce.Do(func() {
		file_nimbus_v1_nimbus_object_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nimbus_v1_nimbus_object_service_proto_rawDesc), len(file_nimbus_v1_nimbus_object_service_proto_rawDesc)))
	})
	return file_nimbus_v1_nimbus_object_service_proto_rawDescData
}

var file_nimbus_v1_nimbus_object_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nimbus_v1_nimbus_object_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nimbus_v1_nimbus_object_service_proto_goTypes = []any{
	(Status)(0),                          // 0: nimbus.v1.Status
	(*CreateOrUpdateObjectRequest)(nil),  // 1: nimbus.v1.CreateOrUpdateObjectRequest
	(*CreateOrUpdateObjectResponse)(nil), // 2: nimbus.v1.CreateOrUpdateObjectResponse
	(*GetObjectRequest)(nil),             // 3: nimbus.v1.GetObjectRequest
	(*GetObjectResponse)(nil),            // 4: nimbus.v1.GetObjectResponse
	(*ObjectDetails)(nil),                // 5: nimbus.v1.types.v1.ObjectDetails
}
var file_nimbus_v1_nimbus_object_service_proto_depIdxs = []int32{
	5, // 0: nimbus.v1.CreateOrUpdateObjectResponse.object_details:type_name -> nimbus.v1.types.v1.ObjectDetails
	1, // 1: nimbus.v1.NimbusObjectService.CreateOrUpdateObject:input_type -> nimbus.v1.CreateOrUpdateObjectRequest
	3, // 2: nimbus.v1.NimbusObjectService.GetObject:input_type -> nimbus.v1.GetObjectRequest
	2, // 3: nimbus.v1.NimbusObjectService.CreateOrUpdateObject:output_type -> nimbus.v1.CreateOrUpdateObjectResponse
	4, // 4: nimbus.v1.NimbusObjectService.GetObject:output_type -> nimbus.v1.GetObjectResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nimbus_v1_nimbus_object_service_proto_init() }
func file_nimbus_v1_nimbus_object_service_proto_init() {
	if File_nimbus_v1_nimbus_object_service_proto != nil {
		return
	}
	file_nimbus_v1_types_v1_files_proto_init()
	file_nimbus_v1_nimbus_object_service_proto_msgTypes[1].OneofWrappers = []any{
		(*CreateOrUpdateObjectResponse_ErrorMessage)(nil),
		(*CreateOrUpdateObjectResponse_ObjectDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nimbus_v1_nimbus_object_service_proto_rawDesc), len(file_nimbus_v1_nimbus_object_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nimbus_v1_nimbus_object_service_proto_goTypes,
		DependencyIndexes: file_nimbus_v1_nimbus_object_service_proto_depIdxs,
		EnumInfos:         file_nimbus_v1_nimbus_object_service_proto_enumTypes,
		MessageInfos:      file_nimbus_v1_nimbus_object_service_proto_msgTypes,
	}.Build()
	File_nimbus_v1_nimbus_object_service_proto = out.File
	file_nimbus_v1_nimbus_object_service_proto_goTypes = nil
	file_nimbus_v1_nimbus_object_service_proto_depIdxs = nil
}
