// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nimbus/v1/nimbus_service.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NimbusService_UpdateAccessType_FullMethodName    = "/nimbus.v1.NimbusService/UpdateAccessType"
	NimbusService_DeleteObject_FullMethodName        = "/nimbus.v1.NimbusService/DeleteObject"
	NimbusService_GetDirectoryContent_FullMethodName = "/nimbus.v1.NimbusService/GetDirectoryContent"
	NimbusService_FindObjectByName_FullMethodName    = "/nimbus.v1.NimbusService/FindObjectByName"
)

// NimbusServiceClient is the client API for NimbusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NimbusServiceClient interface {
	// Update the access type of the object PUBLIC/PRIVATE.
	UpdateAccessType(ctx context.Context, in *UpdateAccessTypeRequest, opts ...grpc.CallOption) (*UpdateAccessTypeResponse, error)
	// Delete an object.
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	// If a valid directory found then returns it objects.
	GetDirectoryContent(ctx context.Context, in *GetDirectoryContentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDirectoryContentResponse], error)
	FindObjectByName(ctx context.Context, in *FindObjectByNameRequest, opts ...grpc.CallOption) (*FindObjectByNameResponse, error)
}

type nimbusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNimbusServiceClient(cc grpc.ClientConnInterface) NimbusServiceClient {
	return &nimbusServiceClient{cc}
}

func (c *nimbusServiceClient) UpdateAccessType(ctx context.Context, in *UpdateAccessTypeRequest, opts ...grpc.CallOption) (*UpdateAccessTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAccessTypeResponse)
	err := c.cc.Invoke(ctx, NimbusService_UpdateAccessType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nimbusServiceClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, NimbusService_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nimbusServiceClient) GetDirectoryContent(ctx context.Context, in *GetDirectoryContentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDirectoryContentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NimbusService_ServiceDesc.Streams[0], NimbusService_GetDirectoryContent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDirectoryContentRequest, GetDirectoryContentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusService_GetDirectoryContentClient = grpc.ServerStreamingClient[GetDirectoryContentResponse]

func (c *nimbusServiceClient) FindObjectByName(ctx context.Context, in *FindObjectByNameRequest, opts ...grpc.CallOption) (*FindObjectByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindObjectByNameResponse)
	err := c.cc.Invoke(ctx, NimbusService_FindObjectByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NimbusServiceServer is the server API for NimbusService service.
// All implementations must embed UnimplementedNimbusServiceServer
// for forward compatibility.
type NimbusServiceServer interface {
	// Update the access type of the object PUBLIC/PRIVATE.
	UpdateAccessType(context.Context, *UpdateAccessTypeRequest) (*UpdateAccessTypeResponse, error)
	// Delete an object.
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	// If a valid directory found then returns it objects.
	GetDirectoryContent(*GetDirectoryContentRequest, grpc.ServerStreamingServer[GetDirectoryContentResponse]) error
	FindObjectByName(context.Context, *FindObjectByNameRequest) (*FindObjectByNameResponse, error)
	mustEmbedUnimplementedNimbusServiceServer()
}

// UnimplementedNimbusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNimbusServiceServer struct{}

func (UnimplementedNimbusServiceServer) UpdateAccessType(context.Context, *UpdateAccessTypeRequest) (*UpdateAccessTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAccessType not implemented")
}
func (UnimplementedNimbusServiceServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedNimbusServiceServer) GetDirectoryContent(*GetDirectoryContentRequest, grpc.ServerStreamingServer[GetDirectoryContentResponse]) error {
	return status.Error(codes.Unimplemented, "method GetDirectoryContent not implemented")
}
func (UnimplementedNimbusServiceServer) FindObjectByName(context.Context, *FindObjectByNameRequest) (*FindObjectByNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindObjectByName not implemented")
}
func (UnimplementedNimbusServiceServer) mustEmbedUnimplementedNimbusServiceServer() {}
func (UnimplementedNimbusServiceServer) testEmbeddedByValue()                       {}

// UnsafeNimbusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NimbusServiceServer will
// result in compilation errors.
type UnsafeNimbusServiceServer interface {
	mustEmbedUnimplementedNimbusServiceServer()
}

func RegisterNimbusServiceServer(s grpc.ServiceRegistrar, srv NimbusServiceServer) {
	// If the following call panics, it indicates UnimplementedNimbusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NimbusService_ServiceDesc, srv)
}

func _NimbusService_UpdateAccessType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccessTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NimbusServiceServer).UpdateAccessType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NimbusService_UpdateAccessType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NimbusServiceServer).UpdateAccessType(ctx, req.(*UpdateAccessTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NimbusService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NimbusServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NimbusService_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NimbusServiceServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NimbusService_GetDirectoryContent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDirectoryContentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NimbusServiceServer).GetDirectoryContent(m, &grpc.GenericServerStream[GetDirectoryContentRequest, GetDirectoryContentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusService_GetDirectoryContentServer = grpc.ServerStreamingServer[GetDirectoryContentResponse]

func _NimbusService_FindObjectByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindObjectByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NimbusServiceServer).FindObjectByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NimbusService_FindObjectByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NimbusServiceServer).FindObjectByName(ctx, req.(*FindObjectByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NimbusService_ServiceDesc is the grpc.ServiceDesc for NimbusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NimbusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nimbus.v1.NimbusService",
	HandlerType: (*NimbusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAccessType",
			Handler:    _NimbusService_UpdateAccessType_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _NimbusService_DeleteObject_Handler,
		},
		{
			MethodName: "FindObjectByName",
			Handler:    _NimbusService_FindObjectByName_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDirectoryContent",
			Handler:       _NimbusService_GetDirectoryContent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nimbus/v1/nimbus_service.proto",
}
