// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nimbus/v1/nimbus_object_service.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NimbusObjectService_CreateOrUpdateObject_FullMethodName = "/nimbus.v1.NimbusObjectService/CreateOrUpdateObject"
	NimbusObjectService_GetObject_FullMethodName            = "/nimbus.v1.NimbusObjectService/GetObject"
)

// NimbusObjectServiceClient is the client API for NimbusObjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This service is only to used to send and recive the raw data bytes.
type NimbusObjectServiceClient interface {
	CreateOrUpdateObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse], error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectResponse], error)
}

type nimbusObjectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNimbusObjectServiceClient(cc grpc.ClientConnInterface) NimbusObjectServiceClient {
	return &nimbusObjectServiceClient{cc}
}

func (c *nimbusObjectServiceClient) CreateOrUpdateObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NimbusObjectService_ServiceDesc.Streams[0], NimbusObjectService_CreateOrUpdateObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusObjectService_CreateOrUpdateObjectClient = grpc.ClientStreamingClient[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]

func (c *nimbusObjectServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NimbusObjectService_ServiceDesc.Streams[1], NimbusObjectService_GetObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetObjectRequest, GetObjectResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusObjectService_GetObjectClient = grpc.ServerStreamingClient[GetObjectResponse]

// NimbusObjectServiceServer is the server API for NimbusObjectService service.
// All implementations must embed UnimplementedNimbusObjectServiceServer
// for forward compatibility.
//
// This service is only to used to send and recive the raw data bytes.
type NimbusObjectServiceServer interface {
	CreateOrUpdateObject(grpc.ClientStreamingServer[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]) error
	GetObject(*GetObjectRequest, grpc.ServerStreamingServer[GetObjectResponse]) error
	mustEmbedUnimplementedNimbusObjectServiceServer()
}

// UnimplementedNimbusObjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNimbusObjectServiceServer struct{}

func (UnimplementedNimbusObjectServiceServer) CreateOrUpdateObject(grpc.ClientStreamingServer[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateOrUpdateObject not implemented")
}
func (UnimplementedNimbusObjectServiceServer) GetObject(*GetObjectRequest, grpc.ServerStreamingServer[GetObjectResponse]) error {
	return status.Error(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedNimbusObjectServiceServer) mustEmbedUnimplementedNimbusObjectServiceServer() {}
func (UnimplementedNimbusObjectServiceServer) testEmbeddedByValue()                             {}

// UnsafeNimbusObjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NimbusObjectServiceServer will
// result in compilation errors.
type UnsafeNimbusObjectServiceServer interface {
	mustEmbedUnimplementedNimbusObjectServiceServer()
}

func RegisterNimbusObjectServiceServer(s grpc.ServiceRegistrar, srv NimbusObjectServiceServer) {
	// If the following call panics, it indicates UnimplementedNimbusObjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NimbusObjectService_ServiceDesc, srv)
}

func _NimbusObjectService_CreateOrUpdateObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NimbusObjectServiceServer).CreateOrUpdateObject(&grpc.GenericServerStream[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusObjectService_CreateOrUpdateObjectServer = grpc.ClientStreamingServer[CreateOrUpdateObjectRequest, CreateOrUpdateObjectResponse]

func _NimbusObjectService_GetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NimbusObjectServiceServer).GetObject(m, &grpc.GenericServerStream[GetObjectRequest, GetObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NimbusObjectService_GetObjectServer = grpc.ServerStreamingServer[GetObjectResponse]

// NimbusObjectService_ServiceDesc is the grpc.ServiceDesc for NimbusObjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NimbusObjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nimbus.v1.NimbusObjectService",
	HandlerType: (*NimbusObjectServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateOrUpdateObject",
			Handler:       _NimbusObjectService_CreateOrUpdateObject_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetObject",
			Handler:       _NimbusObjectService_GetObject_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nimbus/v1/nimbus_object_service.proto",
}
