services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://dev:password@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: password
    networks:
      - db-network

  mongo:
    container_name: nimbus-mongo
    image: mongo:8.0-noble
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
