// @generated
// This file is @generated by prost-build.
/// The authorization sent over the header to access the Objects.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Authorization {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectMetaInfo {
    #[prost(string, tag="1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(enumeration="AccessType", tag="2")]
    pub access_type: i32,
    #[prost(enumeration="ObjectType", tag="3")]
    pub object_type: i32,
    #[prost(map="string, string", tag="4")]
    pub meta_data: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// The access information of an object it can be used via public url or only access using personal access token.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObjectAccessInfo {
    #[prost(string, tag="1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(enumeration="AccessType", tag="2")]
    pub access_type: i32,
}
/// The details of any object it can be file or a directory and the access url if the object is public otherwise it can be only access via personal access token.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectDetails {
    #[prost(enumeration="ObjectType", tag="1")]
    pub object_type: i32,
    #[prost(string, tag="2")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub object_size: u64,
    #[prost(enumeration="AccessType", tag="4")]
    pub access_type: i32,
    #[prost(string, tag="5")]
    pub created_on: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="6")]
    pub meta_data: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// image/jpeg, image/png, text/plain
    #[prost(string, optional, tag="7")]
    pub content_type: ::core::option::Option<::prost::alloc::string::String>,
    /// The access url of a directory is referd as static directory which serve static contents.
    #[prost(string, optional, tag="8")]
    pub access_url: ::core::option::Option<::prost::alloc::string::String>,
}
/// Stream of bytes of the file.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PutObjectRequest {
    #[prost(bytes="vec", tag="1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// After sending the bytes either getting the object response or the error message from the server.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutObjectResponse {
    #[prost(message, optional, tag="1")]
    pub object_details: ::core::option::Option<ObjectDetails>,
}
/// Object id is like the file id, this id must be a file path not a directory or invalid file name.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetObjectRequest {
    #[prost(string, tag="1")]
    pub object_id: ::prost::alloc::string::String,
}
/// The stream of bytes of the file.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetObjectResponse {
    #[prost(bytes="vec", tag="1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteObjectRequest {
    #[prost(string, repeated, tag="1")]
    pub object_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteObjectResponse {
    #[prost(string, repeated, tag="1")]
    pub object_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateAccessTypeRequest {
    #[prost(message, repeated, tag="1")]
    pub object_access_info: ::prost::alloc::vec::Vec<ObjectAccessInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateAccessTypeResponse {
    #[prost(message, repeated, tag="1")]
    pub object_access_info: ::prost::alloc::vec::Vec<ObjectAccessInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDirectoryContentRequest {
    #[prost(string, tag="1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub off_set: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub count: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDirectoryContentResponse {
    #[prost(uint64, tag="1")]
    pub object_count: u64,
    #[prost(message, repeated, tag="4")]
    pub objects: ::prost::alloc::vec::Vec<get_directory_content_response::ObjectInfo>,
}
/// Nested message and enum types in `GetDirectoryContentResponse`.
pub mod get_directory_content_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ObjectInfo {
        #[prost(string, tag="1")]
        pub object_id: ::prost::alloc::string::String,
        #[prost(enumeration="super::AccessType", tag="2")]
        pub access_type: i32,
        #[prost(enumeration="super::ObjectType", tag="3")]
        pub object_type: i32,
        #[prost(string, tag="4")]
        pub content_type: ::prost::alloc::string::String,
        #[prost(string, tag="5")]
        pub created_on: ::prost::alloc::string::String,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FindObjectByIdRequest {
    #[prost(string, tag="1")]
    pub object_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindObjectByIdResponse {
    #[prost(message, optional, tag="1")]
    pub object: ::core::option::Option<ObjectDetails>,
}
/// Either a file or a directory.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ObjectType {
    Unspecified = 0,
    File = 1,
    Directory = 2,
}
impl ObjectType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OBJECT_TYPE_UNSPECIFIED",
            Self::File => "OBJECT_TYPE_FILE",
            Self::Directory => "OBJECT_TYPE_DIRECTORY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OBJECT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "OBJECT_TYPE_FILE" => Some(Self::File),
            "OBJECT_TYPE_DIRECTORY" => Some(Self::Directory),
            _ => None,
        }
    }
}
/// Either Public or Private
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AccessType {
    Unspecified = 0,
    Private = 1,
    Public = 2,
}
impl AccessType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ACCESS_TYPE_UNSPECIFIED",
            Self::Private => "ACCESS_TYPE_PRIVATE",
            Self::Public => "ACCESS_TYPE_PUBLIC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACCESS_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "ACCESS_TYPE_PRIVATE" => Some(Self::Private),
            "ACCESS_TYPE_PUBLIC" => Some(Self::Public),
            _ => None,
        }
    }
}
include!("nimbus_public.v1.tonic.rs");
// @@protoc_insertion_point(module)